import RECEIVE_ITEMS_MESSAGE from "@salesforce/label/c.SBR_3_0_PO_RECEIVE_ITEMS_MESSAGE";
import RECEIVE_ITEMS_ERROR_MESSAGE from "@salesforce/label/c.SBR_3_0_PO_RECEIVE_ITEMS_ERROR_MESSAGE";



const LABELS = {
    RECEIVE_ITEMS_MESSAGE,
    RECEIVE_ITEMS_ERROR_MESSAGE
};

export default LABELS;