public without sharing class SBR_3_0_AVSHelper {
    
    public class Address {
        public String line1 {get; set;}
        public String line2 {get; set;}
        public String city {get; set;}
        public String state {get; set;}
        public String zip {get; set;}
        public String type {get; set;}
        public String company {get; set;}
    }

    public Address address = new Address();
   
}